"""notification

Revision ID: 684c7c82f0f1
Revises: 1e4a933d2025
Create Date: 2025-11-14 10:47:09.316083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684c7c82f0f1'
down_revision = '1e4a933d2025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
