"""schedule

Revision ID: 78833884fd8a
Revises: ea185f498e16
Create Date: 2025-11-17 11:43:39.745358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78833884fd8a'
down_revision = 'ea185f498e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
