"""empty message

Revision ID: b626acd6f0ca
Revises: 684c7c82f0f1
Create Date: 2025-11-14 11:01:54.821659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b626acd6f0ca'
down_revision = '684c7c82f0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_slot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_slot', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('current_slot')
        batch_op.drop_column('max_slot')

    # ### end Alembic commands ###
